Add. Bad Request Exception Handler for OrderEntryException
Bahmni/bahmni-core pull request #228
Opened 2023-08-24 08:44 UTC by deeptirawat1510

Co-authored-by:yenugukeerthana <keerthana.yenugu@thoughtworks.com>

2023-08-24 08:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Bahmni/bahmni-core?pullRequest=228) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Bahmni/bahmni-core?pullRequest=228) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Bahmni/bahmni-core?pullRequest=228) it.</sub>

2023-08-28 05:02 UTC, gsluthra requested changes
Please create a JIRA issue describing the problem and solution. And link this PR to the JIRA issue, and update commit message to contain JIRA issue number. This is required for all "product" code submissions for traceability.

2023-08-28 05:41 UTC, deeptirawat1510 commented
> Please create a JIRA issue describing the problem and solution. And link this PR to the JIRA issue, and update commit message to contain JIRA issue number. This is required for all "product" code submissions for traceability.

@gsluthra done.

2023-08-28 14:30 UTC, gsluthra commented
@deeptirawat1510 - Please sign the CLA (one time activity). Ensure that your commits are associated with the same email address which is associated with your Github account, else you will see a CLA error. You might need to re-push commits (or create new PR), if the email associated with commits is not the same as Github account.

2023-08-28 16:35 UTC, deeptirawat1510 commented
Need to raise PR again since the email associated with commits is not the same as Github account.

2023-08-28 16:35 UTC, closed without merging